version: 2.1

orbs:
  slack: circleci/slack@3.3.0

jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
      - slack/notify:
          message: "Testing"

