version: 2.1

orbs:
  slack: circleci/slack@3.3.0

jobs:
  build:
    docker:
      - image: alpine:3.10

    steps:
      - checkout

      - run:
          name: Greeting
          command: RUN apk update && apk add bash

      - run:
          name: Print the Current Time
          command: date
      - slack/notify:
          message: "Testing"

