version: 2.1


jobs:
  build:
    docker:
      - image: alpine:3.10
    environment:
      BASH: 1
    steps:
      - run:
          name: Install tools
          command: apk add bash curl git
      - slack/notify:
          message: "Started building PR: $CIRCLE_BRANCH started by $CIRCLE_USERNAME"
      - checkout
      - run:
          name: Do something
          command: echo 'export RELEASE="$(date +%Y%m%d)RC$(git rev-parse --short --verify HEAD)"' >> $BASH_ENV
      - slack/status:
          success_message: ":tada: Build $CIRCLE_BRANCH successfull!\n$CIRCLE_USERNAME start deploying!\nto deploy copy paste the following:\n ./deploy REL $RELEASE"

orbs:
  slack: circleci/slack@3.3.0