version: 2.1


jobs:
  build:
    docker:
      - image: alpine:3.10
    environment:
      BASH: 1
    steps:
      - run:
          name: Install tools
          command: apk add bash curl
      - checkout
      - run:
          name: Do something
          command: echo "something"
      - slack/notify:
          message: "Testing"


orbs:
  slack: circleci/slack@3.3.0