version: 2.1


jobs:
  build:
    docker:
      - image: alpine:3.10
    environment:
      BASH: 1
    steps:
      - run:
          name: Install tools
          command: apk add bash curl git
      - checkout
      - run:
          name: Do something
          command: echo 'export RELEASE="$(date +%Y%m%d)RC$(git rev-parse --short --verify HEAD)"' >> $BASH_ENV
      - slack/status:
          include_job_number_field: false
          include_visit_job_action: false


orbs:
  slack: circleci/slack@3.3.0